import { hashSync } from "bcrypt-ts";
const sampleData = {
  users: [
    {
      email: "admin@example.com",
      name: "Admin",
      role: "admin",
      password: hashSync("123456", 10),
    },
    {
      email: "Leon@example.com",
      name: "Leon",
      role: "user",
      password: hashSync("123456", 10),
    },
    {
      email: "Jack@example.com",
      name: "Jack",
      role: "user",
      password: hashSync("123456", 10),
    },
  ],
  products: [
    {
      name: "Summer Meadow Picnic Basket",
      slug: "summer-meadow-picnic-basket",
      category: "Storage",
      description:
        "A beautifully woven rattan picnic basket shown resting in a grassy meadow with a brown fedora hat. Deep enough to carry snacks and essentials for your outdoor adventures.",
      images: ["/images/products/picnic-basket.jpg"],
      price: "89.00",
      brand: "NatureCraft",
      rating: "4.9",
      numReviews: 124,
      countInStock: 25,
      isFeatured: true,
      banner: "/images/products/picnic-basket.jpg",
    },
    {
      name: "Handwoven Rattan Lampshade Collection",
      slug: "handwoven-rattan-lampshade-collection",
      category: "Decor",
      description:
        "A stunning collection of handwoven rattan lampshades featuring both vintage bell shapes and modern dome designs. Perfect for casting warm, ambient light in any room.",
      images: [
        "/images/products/bell-lampshades.jpg",
        "/images/products/dome-lights.jpg",
      ],
      price: "145.00",
      brand: "EcoWeave",
      rating: "4.8",
      numReviews: 89,
      countInStock: 12,
      isFeatured: true,
      banner: "/images/products/bell-lampshades.jpg",
    },
    {
      name: "Assorted Nesting Display Baskets",
      slug: "assorted-nesting-display-baskets",
      category: "Storage",
      description:
        "A versatile wholesale collection of shallow woven baskets and bowls. Ideal for organizing tabletop items, serving bread, or displaying dry goods.",
      images: ["/images/products/assorted-baskets.jpg"],
      price: "68.00",
      brand: "NatureCraft",
      rating: "4.7",
      numReviews: 210,
      countInStock: 50,
      isFeatured: true,
      banner: "/images/products/assorted-baskets.jpg",
    },
    {
      name: "Vintage Rustic Harvest Basket",
      slug: "vintage-rustic-harvest-basket",
      category: "Storage",
      description:
        "An authentic, time-tested bamboo harvesting basket resting on wooden planks. Features a sturdy arched handle, perfect for rustic farmhouse styling.",
      images: ["/images/products/rustic-basket.jpg"],
      price: "120.00",
      brand: "NatureCraft",
      rating: "5.0",
      numReviews: 14,
      countInStock: 3,
      isFeatured: true,
      banner: "/images/products/rustic-basket.jpg",
    },
    {
      name: "Square Woven Coffee Coasters",
      slug: "square-woven-coffee-coasters",
      category: "Tableware",
      description:
        "Finely woven square rattan coasters. Highly heat-resistant to protect your surfaces from hot coffee mugs while complementing your latte art.",
      images: ["/images/products/square-coasters.jpg"],
      price: "24.50",
      brand: "EcoWeave",
      rating: "4.6",
      numReviews: 56,
      countInStock: 100,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Zigzag Patterned Yarn Basket",
      slug: "zigzag-patterned-yarn-basket",
      category: "Storage",
      description:
        "A stylish basket with a distinct zigzag weave and braided handles. Specially designed to hold your knitting needles, yarn balls, and craft supplies neatly.",
      images: ["/images/products/yarn-basket.jpg"],
      price: "55.00",
      brand: "EcoWeave",
      rating: "4.9",
      numReviews: 42,
      countInStock: 0,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Thick Braided Drink Coaster",
      slug: "thick-braided-drink-coaster",
      category: "Tableware",
      description:
        "A chunky, circular braided coaster providing excellent insulation. Perfect for resting a cold glass of water or your favorite citrus drinks.",
      images: ["/images/products/round-coaster.jpg"],
      price: "12.99",
      brand: "NatureCraft",
      rating: "4.5",
      numReviews: 18,
      countInStock: 80,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Elevated Rattan Plant Stand",
      slug: "elevated-rattan-plant-stand",
      category: "Decor",
      description:
        "Give your indoor plants a beautiful home. This woven rattan planter features sturdy wooden legs, shown alongside a stylish patterned tote bag.",
      images: [
        "/images/products/plant-stand-1.jpg",
        "/images/products/plant-stand-2.jpg",
      ],
      price: "110.00",
      brand: "EcoWeave",
      rating: "4.7",
      numReviews: 76,
      countInStock: 20,
      isFeatured: false,
      banner: null,
    },
  ],
};

export default sampleData;
